### ISSUE TITLE
Inconsistent tensor sizes error with own data

### ISSUE THREAD

**Issue by bartolsthoorn** [carpedm20/DiscoGAN-pytorch#1]
I tried out my own dataset in `data/mydata` (with the A and B folders) but I get the following error:
```bash
~/DiscoGAN-pytorch$ python main.py --dataset=mydata --num_gpu=1
[*] MODEL dir: logs/mydata_2017-03-21_14-49-25
[*] PARAM path: logs/mydata_2017-03-21_14-49-25/params.json
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    main(config)
  File "main.py", line 33, in main
    trainer.train()
  File "/home/bart/DiscoGAN-pytorch/trainer.py", line 161, in train
    valid_x_A, valid_x_B = self._get_variable(A_loader.next()), self._get_variable(B_loader.next())
  File "/home/bart/anaconda3/envs/Python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 174, in __next__
    return self._process_next_batch(batch)
  File "/home/bart/anaconda3/envs/Python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 198, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/bart/anaconda3/envs/Python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 32, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/bart/anaconda3/envs/Python36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 68, in default_collate
    return torch.stack(batch, 0)
  File "/home/bart/anaconda3/envs/Python36/lib/python3.6/site-packages/torch/functional.py", line 56, in stack
    return torch.cat(list(t.unsqueeze(dim) for t in sequence), dim)
RuntimeError: inconsistent tensor sizes at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.10_1488755368782/work/torch/lib/TH/generic/THTensorMath.c:2548
```

**Comment by carpedm20** [comment]
What is the size and number of images for each dataset?

**Comment by bartolsthoorn** [comment]
24467 images in A and 1784 images in B.

**Comment by carpedm20** [comment]
What about the resolution? Are they constant for each dataset?

**Comment by bartolsthoorn** [comment]
I did not change anything in the source so it should scale the datasets to
64x64 I suppose. The input images in A and B are of varying size.

**Comment by carpedm20** [comment]
Yeah that should be but that's the only thing that I'm not 100% sure about.. and gotcha that's the reason why the code shows an error

**Comment by carpedm20** [comment]
So pytorch will make a tensor first and then will proceed a scaling. To build a tensor, bached images should be concatenated into a single tensor which makes an error due to different sizes.

**Comment by dandelin** [comment]
Using tools like imagemagick will do.
In my case, 

`mogrify -resize 256x256! -quality 100 -path ../A *.jpg`

 (imagemagick command) solved the issue.

**Comment by carpedm20** [comment]
Yes I updated README.md to contain this issue. Thanks @dandelin!

**Comment by bartolsthoorn** [comment]
Thanks, for scale + center crop:
```
mogrify -resize 256x256^ -gravity center -crop 256x256+0+0 -quality 100 -path ../A *.jpg
```
